Transl4 fr
lxde/lxqt-l10n pull request #161
Opened 2016-11-02 09:50 UTC by paiiou

@pmattern
Can you check, particularly compton-qt, obconf-qt and pavucontrol-qt. I do not know these modules and some translations may be incorrect. 
Thank you

2016-11-02 22:24 UTC, pmattern requested changes
I've left some comments about things I'd consider wrong and others which I think could optionally be improved.
You may want to have a look.

2016-11-02 22:24 UTC, pmattern commented on compton-conf/compton-conf_fr.ts
> +        <translation>Ne pas laisse la luminosité se régler en fonction de l&apos;opacité de la fenêtre</translation>
Should probably be "Ne pas laisse_r_ ..."?

2016-11-02 22:24 UTC, pmattern commented on compton-conf/compton-conf_fr.ts
> +        <translation>Éviter le dondu d&apos;entrée/sortie lors de l&apos;ouverture/fermeture des fenêtres</translation>
Should probably be "Éviter le _f_ondu ...".

2016-11-02 22:24 UTC, pmattern commented on obconf-qt/obconf-qt_fr.ts
> +        <translation>Titres de fenêtre</translation>
Shouldn't "fenêtre" be stated in plural, "Titres des fênetres"?

2016-11-02 22:24 UTC, pmattern commented on obconf-qt/obconf-qt_fr.ts
> +S : Ombre (Enroulé)
"Shade" and "Role" are verbs here, no substantives. So it must be "Ombrer (Enrouler)".

2016-11-02 22:24 UTC, pmattern commented on obconf-qt/obconf-qt_fr.ts
> +        <translation>Affichage &amp;actif et à l&apos;écran :</translation>
Letter "a" is already used as a mnemonic in line 120.
Generally speaking all translations in lines 117-146 belong to the same pane within the GUI so it would be good to avoid duplicate usage of letters in all these mnemonics.

2016-11-02 22:24 UTC, pmattern commented on obconf-qt/obconf-qt_fr.ts
> +        <translation>Focus sur la &amp;nouvelle fenêtre quand elle apparait</translation>
Does "focus" really exist in French?

2016-11-02 22:24 UTC, pmattern commented on obconf-qt/obconf-qt_fr.ts
> +        <translation>Préférez placer de nouvelles fenêtres et &amp;sur :</translation>
In phrases like this you're sometimes using indicative mode like "préférez" here and sometimes infinitive like "centrer" in line 160 above.
I think it would be better to have this consistent, probably best by using the infinitive everywhere.

2016-11-02 22:24 UTC, pmattern commented on obconf-qt/obconf-qt_fr.ts
> +        <translation>Le moniteur principal est l&apos;endroit où Openbox va placer des dialogues, comme celui utilisé pour les fenêtres cycliques.</translation>
"cycling" is not an adjective here but refers to activity cycling. In other words, it is about the dialogues which belong to the tools which are used to cycle through the available windows by keyboard shortcuts, normally `Alt+Tab`.

2016-11-02 22:24 UTC, pmattern commented on obconf-qt/obconf-qt_fr.ts
> +        <translation>Depuis le centre</translation>
Shouldn't this be "Au centre"? Not sure but wondering as "Depuis" is used to describe a distance, like in "Depuis le bord gauche".

2016-11-02 22:24 UTC, pmattern commented on obconf-qt/obconf-qt_fr.ts
> +        <translation>&amp;Délai avant affichage de la notification pour:</translation>
This is not about a delay _until_ the notification is displayed but the time span it will be displayed. So not like "Wait 5 seconds before showing the notification" but "Show notification for 5 seconds."

2016-11-02 22:24 UTC, pmattern commented on pavucontrol-qt/pavucontrol-qt_fr.ts
> +        <translation>Audio muet</translation>
In line 83 the same string was translated as "Audio muet_te_".

2016-11-02 22:24 UTC, pmattern commented on pcmanfm-qt/pcmanfm-qt_fr.ts
>          <translation>Formulaire</translation>
In line 9 of pavucontrol-qt_fr.ts the same string was translated as "dialogue". Just saying.

2016-11-02 22:24 UTC, pmattern commented on pcmanfm-qt/pcmanfm-qt_fr.ts
> +        <translation>Verrouillé</translation>
Should be infinitive "Verrouiller".

2016-11-02 22:24 UTC, pmattern commented on pcmanfm-qt/pcmanfm-qt_fr.ts
> +        <translation>Après de :</translation>
Is it really "Avant _le_" but "Après _de_"?

2016-11-02 22:24 UTC, pmattern commented on pcmanfm-qt/pcmanfm-qt_fr.ts
>          <translation>&amp;Dossiers d&apos;abord</translation>
"folder" is sometimes translated as "répertoire" and sometimes as "dossier". Would it make sense to always use one of those terms only?

2016-11-02 22:24 UTC, pmattern commented on pcmanfm-qt/pcmanfm-qt_fr.ts
>      <messag
"trash" is sometimes translated as "corbeille" and sometimes as "poubelle". Would it make sense to use one of the terms only?

2016-11-02 22:24 UTC, pmattern commented on pcmanfm-qt/pcmanfm-qt_fr.ts
>      <messag
The tab is supposed to display users' home folders here, so `/home/someuser`, not `/`.
Is "répertoire racine" really accurate then?

2016-11-02 22:24 UTC, pmattern commented on pcmanfm-qt/pcmanfm-qt_fr.ts
>      <messag
This means "set the command which is used to change users". It refers to tools like `lxqt-sudo`.
So if I'm not mistaken the current translation is wrong.

2016-11-02 22:24 UTC, pmattern commented on qterminal/qterminal_fr.ts
> +        <translation>Déplacer l&apos;onglet à &amp;droite</translation>
C'est à gauche ici.

2016-11-02 22:24 UTC, pmattern commented on qterminal/qterminal_fr.ts
> +        <translation>Déplacer l&apos;onglet à &amp;gauche</translation>
... et à droite ici.

2016-11-02 22:24 UTC, pmattern commented on qterminal/qterminal_fr.ts
> +        <translation>Zoom &amp;+</translation>
It's "+" here but "entrant" in line 116. Wouldn't it be better to user either a description or a sign in both strings?

2016-11-02 22:24 UTC, pmattern commented on qterminal/qterminal_fr.ts
> +        <translation>Curseur en forme de &amp;clavier</translation>
No. This is not a cursor looking like a keyboard but how the cursor should look like when the keyboard is used.
You may just tweak the setting at Preferences - Appearance - Keyboard cursor Shape to see the meaning.

2016-11-02 22:24 UTC, pmattern commented on qterminal/qterminal_fr.ts
> +        <translation>Curseur en forme de clavier</translation>
(see above)

2016-11-02 22:24 UTC, pmattern commented on qterminal/qterminal_fr.ts
> +        <translation>Synchroniser les marque-pages</translation>
Pas synchroniser mais celles qui ont déja été synchronisées,
"Marque-pages synchronisées" ou quelque chose comme ça.

2016-11-02 22:24 UTC, pmattern commented on qterminal/qterminal_fr.ts
> +        <translation>Marque-page local</translation>
Plural would be better "Marque-pages locales" or so.

2016-11-03 10:44 UTC, paiiou commented on compton-conf/compton-conf_fr.ts
> +        <translation>Ne pas laisse la luminosité se régler en fonction de l&apos;opacité de la fenêtre</translation>
I corrected the mistakes, but not the last of pcmanfm-qt. I have not been able to locate it.
Regarding the word 'focus', it is actually used in French, particularly in computer (according to wikipedia)

2016-11-03 11:04 UTC, pmattern commented
> I corrected the mistakes [...]

Did you by any chance forget to upload? I'm not seeing any changes here.

2016-11-03 12:05 UTC, paiiou commented
Noch ein typo Fehler  : git push --force paiiou tranl4_fr:transl4-fr

2016-11-03 22:45 UTC, pmattern commented
> The tab is supposed to display users' home folders here, so /home/someuser, not /.
Is "répertoire racine" really accurate then?

Corresponding snippet states totally wrong section above. No clue as to why. But you've fixed it nevertheless.

> This means "set the command which is used to change users". It refers to tools like lxqt-sudo.
So if I'm not mistaken the current translation is wrong.

Same problem regarding the snippet but this time the problem persists and should be fixed. See line 1555.

2016-11-07 22:54 UTC, pmattern approved these changes

2016-11-07 23:07 UTC, pmattern commented
I've got aware of your latest fixes only now as there was no further comment after them.
Still both "poubelle" and "corbeille" as well as "répertoire" and "dossier" are used in parallel but I've decided to merge nevertheless. Using e. g. "folder" and "directory is actually not that uncommon in English either so anybody bothered by the parallel usage can drop a note or another PR.

So landed in 84bba92 after squashing the commits.
Merci encore.

2016-11-07 23:07 UTC, closed without merging